### ISSUE TITLE
Add Support for Kubernetes ingress controller

### ISSUE THREAD

**Issue by VincentFRS** [luraproject/lura#265]
Please, add support for Kubernetes Ingress Controller.
It will be very Helpfull for Kubernetes intégration

**Comment by kpacha** [comment]
@VincentFRS , doesn't https://github.com/mikescandy/krakend-helm cover your requirements?

**Comment by VincentFRS** [comment]
Yes i think, we will test this solution shortly.

Thanks

**Comment by VincentFRS** [comment]
Hello again, 
The Helm configuration from mike has an ingress configuration for KrakenD.
But i mean an ingress Controler like [(NGinx Ingress Controller)](https://github.com/kubernetes/ingress-nginx)
With that we could configure the endpoints in the kubernetes deployment of the services.
(Sorry for the bad english)

**Comment by kpacha** [comment]
> With that we could configure the endpoints in the kubernetes deployment of the services.

does this mean you want an automatically generated and updated gateway definition/contract? because, IMHO, that's not a good practice. here you'll find more about that point: https://www.krakend.io/blog/deploying-an-api-gateway/

so, no, there is no KrakenD ingress controller.

cheers

**Comment by VincentFRS** [comment]
I did'nt mean automatically, it will be a **manual** configuration inside the service repository. We will not modify existing api contracts, just deploy new ones.
The purpose is to have a full versioned configuration by code and to have a fully automatic deployment.

If this is not your original goal with Krakend, im okay with that :)

**Comment by alombarte** [comment]
Hi @VincentFRS 

First of all, let me say my knowledge of Kubernetes is limited, but usually, all users of krakend get your purpose --> versioned configuration and automatic deployment. The way we do it is by generating the immutable docker container with the configuration inside, and it gets automatically deployed through a pipeline.

I understand that you are requesting this IngressController to version only the yml file which would contain the configuration of KrakenD embedded, and you would skip the part of generating of the immutable container and attaching the provided configuration.

Is my understanding right?

**Comment by SantoshSah** [comment]
@alombarte , i am expecting Krakend to be exposed as [Ingress Controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) for Kubernetes. I think @VincentFRS is also expecting same.

**Comment by VincentFRS** [comment]
My Knowledge of KrakenD il limited but an Ingress Controller is dynamic in Kubernetes. He allows to deploy a new service URL dynamically with an ingress configuration. 
If KrakenD require a new deployment to do that, it will be difficult to be exposed as an Ingress Controller.
Thanks again for the response.

**Comment by kpacha** [comment]
> an Ingress Controller is dynamic in Kubernetes. He allows to deploy a new service URL dynamically with an ingress configuration.

and that's why there is no ingress controller for KrakenD. Expose your KrakenD over your default ingress controller and let the KrakenD deal with explicit endpoint configurations.

**Comment by SantoshSah** [comment]
@kpacha , any example of exposing KrakenD over ingress controller?

**Comment by kpacha** [comment]
https://github.com/mikescandy/krakend-helm/blob/master/templates/ingress.yaml configures the ingress controller for the gateway

https://www.krakend.io/blog/krakend-on-kubernetes/ exposes the gateway as a `NodePort`service

**Comment by Dhua-v** [comment]
Hi, @kpacha . I see that ingress controllers are loaded as a library file by kubernetes, and run in the same process as of kubernetes. However, in current way, request is first read by kubernetes and then krakenD. Hence, latency added twice.

Isn't it. Please verify and correct if wrong.

**Comment by Dhua-v** [comment]
Can't we have this https://github.com/Kong/kubernetes-ingress-controller , we can just port it for krakenD. The best api gateway.

**Comment by kpacha** [comment]
> Hi, @kpacha . I see that ingress controllers are loaded as a library file by kubernetes, and run in the same process as of kubernetes.

I think that's not how it works... if you check the ingress controller you linked, you'll see it's a binary running a client to communicate with the gateway control plane. there are at least 2 processes here: k8s and the ingress controller (and maybe a third one for the gateway itself)

**Comment by Dhua-v** [comment]
then in that case, our current implementation would be efficient.

Thanks

**Comment by rr-tomas-henriquez** [comment]
Just adding to this talk:

* Krakend is not fit for an ingress controller because of it non-dynamic nature
* It really sucks to have to do double jumps, meaning, to enter kubernetes requests would need to go to nginx, then krakend, then the destination

A way to fix this is to add krakend outside of kubernetes but that will complicate the deployment stack. On my side I have been trying to figure out how to get this done properly and this is the only solution I have found.

**Comment by Dhua-v** [comment]
have krakend as a simple load balancer. I see no benifit for using it as an ingress.

**Comment by ervinb** [comment]
@rr-tomas-henriquez Having a Service ( `type: LoadBalancer`) backed by a NLB for example would solve the "double jump" issue right? Or am I missing something?

**Comment by rr-tomas-henriquez** [comment]
My comment is very old when Lua was KrakenD, I am not sure if things have changed but at the time of my comment, Lua was an application so it couldn't be setup as an Ingress, meaning, a call would hit the ingress (NLB on this case) and the the Lua app to proxy the calls you need.

The double jump I talk about is that one:

```
NLB (Ingress jump 1)  --> Lua app to forward call to services (jump 2) --> services
```

**Comment by ervinb** [comment]
Thanks for the clarification; I pictured the following when I read your comment:
```
NLB -> nginx (IC) -> krakend -> services
```

**Comment by alombarte** [comment]
I am closing this task as it belonged initially to KrakenD, but it is out of scope in Lura. Lura is a library to build gateways, and creating an ingress is out of the project.
