### ISSUE TITLE
Getting Error Invalid Status code for response with success http status code other than 201 and 200

### ISSUE THREAD

**Issue by abdulrahmank** [luraproject/lura#283]
**Describe the bug**
Getting Error Invalid Status code for response with success http status code other than 201 and 200

**To Reproduce**
1. Create an endpoint with a backend that returns 2XX other than 200 and 201

**Expected behavior**
All the RFC successful status code should be treated as success.

**Comment by kpacha** [comment]
hi @abdulrahmank and welcome to the KrakenD community!

this is the expected behaviour. Please, take a look at https://www.krakend.io/docs/faq/#i-am-getting-a-500-status-when-the-backend-returns-anything-but-200-201-or-redirects
