### ISSUE TITLE
Submit https request using http1.1 protocol

### ISSUE THREAD

**Issue by tanggary** [luraproject/lura#285]
Hello, I'm a newcomer to Krakend.

I've configured an endpoint that has a backend that utilizes https with client certificates.
However, I get this error when making the request to the endpoint.

[GIN] 2019/09/19 - 00:37:55 | 500 | 558.632168ms | ##.###.##.## | GET /dev
Error #1: Get https://###########/thunder/kale: stream error: stream ID 3; HTTP_1_1_REQUIRED

It seems like Krakend will only submit https requests with http2 protocol.
Is there a way we can configure which http protocol a request can use?

**Comment by taik0** [comment]
You need to set up your http Client (modifying the lura client, or creating a new one in a plugin).

The setup needed to force HTTP1.1 would be something like this:
```
&http.Transport{
	TLSNextProto: map[string]func(string, *tls.Conn) http.RoundTripper{},
},
```
