### ISSUE TITLE
Support echo router

### ISSUE THREAD

**Issue by mstrYoda** [luraproject/lura#298]
It would be nice to support echo framework as well.

**Comment by musinit** [comment]
I agree, are there any plans for that? Will happy to prepare PR for that. @kpacha

**Comment by alombarte** [comment]
Thank you @mstrYoda and @musinit, we've listened to the proposal. At the moment we do not have plans to make echo router available in the near future, but all feedback is taken into account for future developments.

Feel free to explain why this is important to you and how this addition is going to help the community as a whole. You can always submit a PR for review.

Make sure to upvote :+1: features, at least we have some reference of who is looking for this.

Thanks

**Comment by alombarte** [comment]
7 votes since 2019. I am closing the issue.

Thanks!
