### ISSUE TITLE
How to cache backend responses?

### ISSUE THREAD

**Issue by granty1** [luraproject/lura#335]
**Describe the bug**
I was interested in caching, so I tested it, but the result was a little confusing

**To Reproduce**
1. Configuration used
```
// port 8000
.....
.....
{
     "endpoint": "/page",
     "backend": [
        {
          "url_pattern": "/page",
          "host": [
             "http://127.0.0.1:8001"
          ],
          "extra_config": {
            "github.com/devopsfaith/krakend-httpcache": {}
          }
        }
      ]
}
```
2. Then i just run krakend-ce , and call endpoint multiple times
```
curl -i "http://127.0.0.1:8000/page"
```

3. However, every time the backend has a requested log, it is not cached after the first request 
4. I noticed that krakend uses sony's go-breaker and gets cache time from `Cache-Control`. my response header also has `Cache-Control`

**Expected behavior**
Only the first request has a log in the backend, and the rest should use the response in the cache

**Logs**
Krakend-ce:
[GIN] 2020/03/13 - 12:20:13 | 200 |    2.541701ms |       127.0.0.1 | GET      /page
[GIN] 2020/03/13 - 12:20:13 | 200 |    1.019577ms |       127.0.0.1 | GET      /page
[GIN] 2020/03/13 - 12:20:14 | 200 |     683.903µs |       127.0.0.1 | GET      /page

Servers:
[GIN] 2020/03/13 - 12:20:13 | 200 |    1.396364ms |       127.0.0.1 | GET      /page
[GIN] 2020/03/13 - 12:20:13 | 200 |     342.851µs |       127.0.0.1 | GET      /page
[GIN] 2020/03/13 - 12:20:14 | 200 |     202.322µs |       127.0.0.1 | GET      /page
**Additional context**

**Comment by fabiopovoa** [comment]
Any updates? It seems the memory consumption increases, but the cache is not working.

**Comment by fabiopovoa** [comment]
1. Endpoint configuration

`{
      "endpoint": "/test",
      "method": "GET",
      "cache_ttl": "10s",
      "backend": [
        {
          "host": "http://localhost:8083",
          "url_pattern": "/test",
          "extra_config": {
            "github.com/devopsfaith/krakend-httpcache": {}
          }
        }
      ]
    }`

2. curl output

`HTTP/1.1 200 OK
Cache-Control: public, max-age=10
Content-Type: application/json; charset=utf-8
X-Krakend: Version 1.3.0
X-Krakend-Completed: true
Date: Mon, 22 Mar 2021 18:01:18 GMT
Content-Length: 19
`

**Comment by kpacha** [comment]
hi, @fabiopovoa 

sorry for the delay. this issue got totally missed.

can you also share the headers from your backend response?

**Comment by fabiopovoa** [comment]
Here it goes.

`
HTTP/1.1 200 
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 22 Mar 2021 18:24:46 GMT
`

It's a simple springboot backend designed only for testing.

**Comment by kpacha** [comment]
from the [documentation](https://www.krakend.io/docs/backends/caching/):

> When enabled all connections for the configured backend are cached in-memory for the amount of time retrieved from the Cache-Control header of the response.

add the header `Cache-Control: public, max-age=10` to your backend responses and the cache will kick in

**Comment by fabiopovoa** [comment]
Still the same problem. 

`HTTP/1.1 200 
Cache-Control: public, max-age=10
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 22 Mar 2021 19:01:05 GMT`

**Comment by kpacha** [comment]
I'm confident the component works. It's running on several production environments and you can test it using the config from our integration tests: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L318-L356

the external service returns this header block:

```
HTTP/1.1 200 OK
Date: Mon, 22 Mar 2021 19:13:22 GMT
Content-Type: text/xml; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=da91f16bdd237b5e39bad1877c58be99a1616440402; expires=Wed, 21-Apr-21 19:13:22 GMT; path=/; domain=.showrss.info; HttpOnly; SameSite=Lax
Cache-Control: max-age=600, public
Set-Cookie: XSRF-TOKEN=eyJpdiI6InV1VVZ4NWsyejlOc3UxOEEzVmhydEE9PSIsInZhbHVlIjoielo2QVpYS1FmYnZ6dHZOcWc2Z0JHVWlHUFwvSkprQXlBXC9xOXRMV0NTRitGc0RjWlJtcE0wMWFMVDNCcUJEV01zIiwibWFjIjoiZjRlZjAzZTMxZTFkYzI1NThhN2FlNGI1M2Y1ZDc5YTI0MWUyODFlNmQ3MWRjMDA2NWNiMzUwMDhhZGE5MjdjOCJ9; expires=Mon, 22-Mar-2021 21:13:22 GMT; Max-Age=7200; path=/
CF-Cache-Status: BYPASS
cf-request-id: 08fcf4393700004de22b3dc000000001
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=BDxby5lFi1cuObV5U%2BH6ap9jRaO7qtg1r4KXapFme7UFqhbVmKQIdc2xmU0soINe9dSx1lOGfq4KV6W1KExDThRwMLUcB1PoNsHf0oc%3D"}],"max_age":604800}
NEL: {"max_age":604800,"report_to":"cf-nel"}
Server: cloudflare
CF-RAY: 6341bca1fd004de2-FRA
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

I'm not sure about what is the difference between this response and the one from your backend

**Comment by fabiopovoa** [comment]
I am sorry to insist, but I am missing something. 

In the example you provided, how do you test if the response actually comes from the cache?

**Comment by kpacha** [comment]
1) start the tcpdump
```
$ sudo tcpdump -vvAls0 | grep 'Host: showrss.info'
tcpdump: listening on enp4s0, link-type EN10MB (Ethernet), capture size 262144 bytes
```

2) start your krakend instance (with the config from the integration tests)

3) after sending the first request to http://localhost:8080/show/12345, you'll see this output from the tcpdump console:
```
	Host: showrss.info
Host: showrss.info
	Host: showrss.info
Host: showrss.info
``` 

4) the next calls to http://localhost:8080/show/12345 won't generate any output on the tcpdump console because the httpcache component is kicking in

cheers

**Comment by victor-bortone** [comment]
I found out something that corroborates the behaviour described by @granty1 and @fabiopovoa. When the backend uses "Transfer-Encoding: chunked", httpcache component doesn't kick in and it hits the backend endpoint every single time. Shouldn't this behaviour be treated as a bug?

**Comment by kpacha** [comment]
@victor-bortone , can you provide a way to reproduce it? As I already commented, I'm not able to reproduce such issue

**Comment by victor-bortone** [comment]
Sure, @kpacha , here it is: https://github.com/victor-bortone/krakend-cache-test
I hope it helps you.

**Comment by kpacha** [comment]
thanks for that. Now I have seen it failing so I'm tagging the issue as bug (the tag could be removed after further investigation). 

I've been doing some testing and so far I can't pinpoint the difference that triggers the undesired behaviour. I will check your backend with the underlying lib, because it was working as expected with all the synthetic tests I tried.

**Comment by kpacha** [comment]
I finally found the problem. the CE will use a fork from the original package until it gets fixed.

Again, thanks for the heads up and for sharing a way to reproduce it

**Comment by Perfeto** [comment]
Hi guys! I forgot that it does not work with `no-op`. I hope it will help someone.
