### ISSUE TITLE
Kafka integration error

### ISSUE THREAD

**Issue by juanvasquezreyes** [luraproject/lura#351]
I have two endpoints one as a consumer and another one as a producer

the producer works fine, while the consumer is giving me this error
[GIN] 2020/04/09 - 14:56:20 | 200 |    12.95788ms |   10.207.130.35 | POST     /kafkain
**[GIN] 2020/04/09 - 14:56:26 | 500 |     337.238µs |   10.207.130.35 | POST     /kafkaout
Error #01: invalid character 'e' in literal true (expecting 'r')**

If I use kafka consumer, I can see the messages given by the producer
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic krakend

this is my krakend.json file
"endpoints": [{
            "endpoint": "/kafkain",
            "method": "POST",
            "extra_config": {},
            "output_encoding": "json",
            "concurrent_calls": 1,
            "backend": [{
              "url_pattern": "/",
              "encoding": "json",
              "sd": "static",
              "extra_config": {
                "github.com/devopsfaith/krakend-pubsub/publisher": {
                    "topic_url": "krakend"
                }
              },
              "method": "GET",
              "host": [
                "kafka://"
              ],
              "disable_host_sanitize": true
            }]
    }, {
            "endpoint": "/kafkaout",
            "method": "POST",
            "extra_config": {},
            "concurrent_calls": 1,
            "backend": [{
              "url_pattern": "/",
              "sd": "static",
              "extra_config": {
                "github.com/devopsfaith/krakend-pubsub/subscriber": {
                    "subscription_url": "group?topic=krakend"
                  }
                },
              "method": "GET",
              "host": [
                "kafka://"
              ],
              "disable_host_sanitize": true
            }]

can you help me figuring out what I did wrong?

**Comment by alombarte** [comment]
If you still face this issue, please open it on KrakenD. Lura does not have Kafka integration.
