### ISSUE TITLE
Abstracting Server and Version info

### ISSUE THREAD

**Issue by pilayar76** [luraproject/lura#390]
**Describe the bug**
Guys, I am new to KrackenD and migrating from Nginx/Openresty. My requirements are to achieve all the features from Nginx along with API Gateway feature like throttling, rate limiting.

During this process, I would like to abstract the server/version information in Response headers, but no luck so far. Am i missing something? Kindly help.

**To Reproduce**
Make any call and it returns as below.

```
User-Agent: curl/7.47.0
Accept: */*

HTTP/1.1 200 OK
Cache-Control: public, max-age=300
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Krakend: Version 1.1.1
X-Krakend-Completed: true
X-Xss-Protection: 1; mode=block
Date: Wed, 08 Jul 2020 02:41:46 GMT
```

**Expected behavior**
```
User-Agent: curl/7.47.0
Accept: */*

HTTP/1.1 200 OK
Cache-Control: public, max-age=300
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Wed, 08 Jul 2020 02:41:46 GMT
```

**Removed X-Krakend Headers**

**Logs**
If applicable, any logs and debugging information

**Additional context**
Do we have an option in KrakenD like server_tokens off/more_clear_headers in Nginx.

**Comment by alombarte** [comment]
Hi,

This is how to do it:
```
{
  "version": 3,
  "extra_config": {
    "router": {
       "hide_version_header": true
    }
  }
}
```
