### ISSUE TITLE
Request manipulation 

### ISSUE THREAD

**Issue by FeyverkSoft** [luraproject/lura#421]
I have 2 backends point.
But they accept fields with different names as input.
/test1 {"email": "sdfsdfs@sdsd.sd"}
/test2 {"login": "sdfsdfs@sdsd.sd"}
"mapping" changes fields only in the response, but not in the request :(
How to make it so that the request would also change.
```
      "backend": [
        {
          "url_pattern": "/test1",
          "host": [
            "http://localhost"
          ],
          "mapping": {
            "login": "email"
          }
        },
        {
          "url_pattern": "/test2",
          "host": [
            "http://localhost"
          ]
        }
      ]
```

**Comment by alombarte** [comment]
Mapping only works in the response context. There is no modifier for the request.
