### ISSUE TITLE
Disable log for a specific endpoint

### ISSUE THREAD

**Issue by leonardoloch** [luraproject/lura#422]
I'm faced a problem that is always a endpoint have been called by a load balance, this endpoint is a health check, and the log stream is messy, a lot of request.

I would like that through a field indicate that a specific endpoint does not log.

**Comment by alombarte** [comment]
Hi @leonardoloch ,

It's been a while since you opened this issue...

This is how to do it
```
{
  "version": 3,
  "extra_config": {
    "router": {
      "@comment": "The health endpoint checks do not show in the logs",
      "logger_skip_paths": [
        "/__health"
      ]
    }
  }
}
```
