### ISSUE TITLE
Krakend returns 500 status code with backend returning 201

### ISSUE THREAD

**Issue by riibeirogabriel** [luraproject/lura#424]
**Describe the bug**
The krakend is returning the 500 status code with backend returning 201, i think that can be a timeout issue, but i didn't find in docs if there is a default timeout.

**Comment by kpacha** [comment]
the default is 2 seconds.
https://github.com/devopsfaith/krakend/blob/master/config/config.go#L26

timeouts are logged, so you should see a message if the timeout is reached. I'd check how the actual backend response looks like, because there could be a problem with the response decoder.

https://www.krakend.io/docs/faq/

**Comment by riibeirogabriel** [comment]
According with this [docs ](https://www.krakend.io/docs/throttling/timeouts/) i put the `timeout : 0s` in krakend.json root, but the 500 status code persists, i think wich the timeout was not removed.

**Comment by riibeirogabriel** [comment]
@kpacha If i set the `timeout : 0s` in krakend.json root, the timeout must be removed?

**Comment by kpacha** [comment]
> According with this docs i put the timeout : 0s in krakend.json root, but the 500 status code persists, i think wich the timeout was not removed.
that's not correct. the documentation shows how the other timeouts (the ones related to the router, such as `write_timeout`) can be undefined but not the service/endpoint `timeout`. it should be always defined, and going with a 0 will fallback into the default one (2s).

Do you see anything at the logs? Can you share your configuration and a sample backend response?

**Comment by riibeirogabriel** [comment]
I don't know how see the krakend logs in docker swarm, i will take a look in the docs, 

There is nothing in krakend responde, only the 500 status code, but the backend returns 201 when i check in backend logs.
![image](https://user-images.githubusercontent.com/33736256/97480160-d0141100-1931-11eb-9642-e5443160fd5a.png)

[Here](https://github.com/learningOrchestra/learningOrchestra/blob/feature-learning-orchestra-api/microservices/krakend/krakend.json) is my krakend.json

There is no option to remove the timeout in krakend?

**Comment by riibeirogabriel** [comment]
I am working on software which rely from external resources ( varying the size of resources from KiB to GiB) to accomplish a request, then there is no way predict a time to each request processing.

**Comment by kpacha** [comment]
without logs or a sample response from the backend returning the 201 I can't help you.

regarding the request processing time, if it's over a second you should go with a more async approach. 

finally, notice that you can't remove the timeout but you can push it as far as you wish ("timeout":"3600s" is a valid configuration)

**Comment by riibeirogabriel** [comment]
okay, i will change my backend to async way, thanks! if i make a GET request from a huge image (e.g 100 MiB), it can make a timeout on krakend?

**Comment by kpacha** [comment]
> okay, i will change my backend to async way, thanks! if i make a GET request from a huge image (e.g 100 MiB), it can make a timeout on krakend?

yes, depending on the configured timeout and the actual latency of the process
