### ISSUE TITLE
Allow sequential proxy to also use variables in backend host parameter

### ISSUE THREAD

**Issue by cadavre** [luraproject/lura#425]
**Is your feature request related to a problem? Please describe.**

I have dynamic backend, a single one based on one of request parameters. To fetch this backend's host I need to use chained sub-request – it gives me a hostname I need to use.

Currently I can use variables that references the response of a previous API call only in `url_pattern`. Why not expand it to also `backend.host`?

**Describe the solution you'd like**

I'd like to use variables that references the response of a previous API call in `backend.host`.

**Describe alternatives you've considered**

I tried nginx with auth_request and njs. In KrakenD I cannot achieve what I need.

**Additional context**

None.

**Comment by JGMAGNO** [comment]
I dont know if this will answer your question, but I am able to call backend host inside .env file

https://github.com/devopsfaith/krakend/issues/408
