### ISSUE TITLE
Rate-limiting based of JWT claim

### ISSUE THREAD

**Issue by ozonni** [luraproject/lura#432]
Is it possible to configure rate-limit based on a custom claim inside JWT token?
If not then is it possible to implement this behavior by writing custom plugin in go-lang?

**Comment by brunobastosg** [comment]
@ozonni If you're interested, we had to implement this feature recently. Code is here: https://github.com/brunobastosg/krakend-ratelimit/tree/ratelimit-per-jwt-claim

**Comment by alombarte** [comment]
Closing this issue as authorization is not in the scope of the Lura project. 

Feel free to open an issue on KrakenD if you are still interested.
