### ISSUE TITLE
Unsupported method HEAD

### ISSUE THREAD

**Issue by nickwww** [luraproject/lura#436]
I'm trying to run an upload server behind a krakend gateway. It is based on https://tus.io. It needs several endpoints (POST, HEAD, PATCH). I found the endpoint using the HEAD method is not available. Is there a reason this is not supported? Could this be added in future releases? From a brief search I found the gin router supports the HEAD method in general. 

BTW: Thanks for creating krakend!

**Comment by ZainulSaifulah** [comment]
any update about HEAD method support for the next release?

**Comment by saffari-m** [comment]
@nickwww Hi, do you have any update?

**Comment by Pythonov** [comment]
Hi!
I have the same problem as [nickwww](https://github.com/nickwww)
Any news about that?

**Comment by RubyKozel** [comment]
Why isn't this being progressed? 
This is completely blocking us from using Krakend without the HEAD support
I see there's a PR read - what is the blocker here?

**Comment by kpacha** [comment]
@RubyKozel check my comment on the PR https://github.com/luraproject/lura/pull/532#issuecomment-963348189
