### ISSUE TITLE
Call backends in sequence and use array from response in subsequent backend call

### ISSUE THREAD

**Issue by Gyllsdorff** [luraproject/lura#447]
**Is your feature request related to a problem? Please describe.**
We have one service that returns a array of items, each item have a ID that is unique. We want to use the api gateway to call another service with all of the id:s in the first request. 

<details><summary>Example</summary>

Service 1
`GET /service1/items`
```json
{
    "count": 2,
    "items": [{
        "id": "43432",
        "title": "foo"
    }, {
        "id": "1214",
        "title": "bar",
    }]
}
```

Service 2
`GET /service2/data?id=43432&id=1214`
```json
{
    "count": 2,
    "items": [{
        "id": "43432",
        "data": "data 1"
    }, {
        "id": "1214",
        "data": "data 2"
    }]
}
```

Final
```json
{
    "count": 2,
    "service1": [{
        "id": "43432",
        "title": "foo"
    }, {
        "id": "1214",
        "title": "bar",
    }],
    "service2": [{
        "id": "43432",
        "data": "data 1"
    }, {
        "id": "1214",
        "data": "data 2"
    }]
}
```
</details>

**Describe the solution you'd like**
1. Use [Sequential proxy](https://www.krakend.io/docs/endpoints/sequential-proxy/) to call the backends sequentiall.
2. Use `flatmap_filter` to move all id:s to a new array.
3. Have a documented way on how to forward array query parameters.

<details><summary>KrakenD config</summary>

```json
{
  "version": 2,
  "@comment": "The host parameter is set by a ENV variable, but it needs something in this file that can be overriden.",
  "host": "http://localhost:20076",
  "port": "20240",
  "endpoints": [
    {
      "endpoint": "/test1",
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
          "sequential": true
        }
      },
      "headers_to_pass": [
        "Authorization",
        "User-Agent"
      ],
      "backend": [
        {
          "url_pattern": "/service1/items",
          "extra_config": {
            "github.com/devopsfaith/krakend/proxy": {
              "flatmap_filter": [
                {
                  "type": "move",
                  "args": [
                    "items.*.id",
                    "ids"
                  ]
                }
              ]
            }
          }
        },
        {
          "url_pattern": "/service2/data?id={resp0_ids}"
        }
      ]
    }
  ]
}
```

**Additional context**
We will likely also want to merge the arrays using a specific field as the key, but we can handle that in a plugin.

**Comment by mgogh** [comment]
Did you find a solution ? I would like to do the same but I didn't find any examples or solutions making this stuff works.

Regards,

**Comment by yuyinhao** [comment]
Multiple {resp0_ids}  will become one, because it's not a collection

**Comment by qasim-nawaz-optiva** [comment]
@yuyinhao for me with this approach it doesn;t parse {resp0_id} and calls the url with the same place holder !
my encoding is :safejson

**Comment by amiranbarigreenweb** [comment]
Did you find a solution ? I would like to do the same but I didn't find any examples or solutions making this stuff works.

Regards,

**Comment by amiranbari** [comment]
Did you find a solution ?

**Comment by Powa458** [comment]
Any update on that?

**Comment by alombarte** [comment]
Hi,

You cannot forward an array of items unless you flatten them to a string. Flatmap does not have this feature, as it is designed to return objects or collections, but we are open to accepting any contributions in that sense.

That being said, for those looking for a solution to this problem without recoding the framework, the only option I can think of is to use the KrakenD Enterprise component that allows you to do projections, flattening, and all sorts of magics.

In the example you have passed where you would receive a response in the backend like:
```{
  "items": [
    {"id": 1},
    {"id": 2}
  ]
}
```
You could have a simple inclusion like:
```
{
    "url_pattern": "/service1/items",
    "extra_config": {
        "modifier/jmespath": {
            "expr": "{ids: items[].to_string(id) | join(',',@)}"
        }
    }
}
```
which would produce a backend response like:
```
{
  "ids": "1,2"
}
```
Now this object is injectable by sequential without any problem.

I am closing the issue as there is no workaround inside Lura
