### ISSUE TITLE
Passing claims array to query params

### ISSUE THREAD

**Issue by dalmenar** [luraproject/lura#482]
It's really suprised about krakend documentation...so good! I'm was checking this section:

https://www.krakend.io/docs/authorization/jwt-validation/#passing-claims-to-the-backend-url

But in my case, the claim is an array. So, I trying to do something like this:

JWT: { components:["XXX","YYYY"] }
Enter URL: api/v1/components
Backend url: api/v1/components?idComponent=XXXX&idComponent=YYYY

I try in another case when the claim is only a field, pero i don't know how to do when is an array. 

I check lua script but i don't know to get access to JWT Claims... 

`
 "github.com/devopsfaith/krakend-lua/router": {
           "pre": "local req = ctx.load() ; req:query(\"user\", req:headers(\"x-user\")) "
        }
`
Thanks!!!

**Comment by kpacha** [comment]
you could use this hack: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/lua/collection.lua#L1-L10

or wait until https://github.com/devopsfaith/krakend-jose/pull/64 gets merged and just pass the values as a comma-separated value

**Comment by kpacha** [comment]
@dalmenar please, open an issue at the lua project: https://github.com/devopsfaith/krakend-lua/

**Comment by dalmenar** [comment]
Ok! Sorry!
