### ISSUE TITLE
repo module path bug

### ISSUE THREAD

**Issue by xushaoxiao** [luraproject/lura#492]
**Describe the bug**
go: github.com/luraproject/lura/config: github.com/luraproject/lura@v1.3.0: parsing go.mod:
        module declares its path as: github.com/devopsfaith/krakend
                but was required as: github.com/luraproject/lura

![image](https://user-images.githubusercontent.com/83151234/119111444-a64d4380-ba55-11eb-9f83-23fce777d55e.png)

**Comment by muskose** [comment]
I have the same problem.

` go get -u all
   go get: github.com/luraproject/lura@v0.9.0 updating to
        github.com/luraproject/lura@v1.3.0: parsing go.mod:
        module declares its path as: github.com/devopsfaith/krakend
       
                but was required as: github.com/luraproject/lura
`

**Comment by muskose** [comment]
I have the same problem.

`go get -u all

go get: github.com/luraproject/lura@v0.9.0 updating to
		github.com/luraproject/lura@v1.3.0: parsing go.mod:
		module declares its path as: github.com/devopsfaith/krakend
				but was required as: github.com/luraproject/lura`

**Comment by kpacha** [comment]
we are in the process of moving the repo: https://github.com/luraproject/lura/pull/487
