### ISSUE TITLE
JWT Validator returning error that Error #01: square/go-jose: unsupported key type/format

### ISSUE THREAD

**Issue by suyogw03** [luraproject/lura#503]
**Describe the bug**
I am trying to integrate JWT Signer and Validator in KrakenD Gateway, the gateway has successfully signed the JWT token and return it, but when I pass that JWT token to one of the backend endpoint, It is throwing an error that Error #01: square/go-jose: unsupported key type/format

**Logs**
`
[GIN] 2021/06/26 - 05:22:23 | 401 |       8.576µs |      172.17.0.1 | GET      "/gateway/simple"
Error #01: Token not found
[GIN] 2021/06/26 - 05:22:24 | 401 |       6.359µs |      172.17.0.1 | GET      "/gateway/simple"
Error #01: Token not found
[GIN] 2021/06/26 - 05:23:14 | 401 |    4.629282ms |      172.17.0.1 | GET      "/gateway/simple"
Error #01: square/go-jose: unsupported key type/format
[GIN] 2021/06/26 - 05:23:44 | 401 |       7.517µs |      172.17.0.1 | GET      "/gateway/simple"
Error #01: Token not found
[GIN] 2021/06/26 - 05:23:48 | 401 |       7.062µs |      172.17.0.1 | GET      "/gateway/simple"
Error #01: Token not found
[GIN] 2021/06/26 - 05:24:25 | 401 |    4.802904ms |      172.17.0.1 | GET      "/gateway/simple"
Error #01: square/go-jose: unsupported key type/format
[GIN] 2021/06/26 - 05:30:31 | 401 |    4.579045ms |      172.17.0.1 | GET      "/gateway/simple"
Error #01: square/go-jose: unsupported key type/format
`

**Comment by lakshay2k09** [comment]
Did you get any solution to your issue. I am also working on same part. Do help and suggest if you got the problem solved.

**Comment by alombarte** [comment]
This is not a component of Lura. Closing.
