### ISSUE TITLE
Select endpoint based on host in http request

### ISSUE THREAD

**Issue by peterzandbergen** [luraproject/lura#505]
**Is your feature request related to a problem? Please describe.**
Is it possible to select an endpoint not only on the path in the HTTP request, but also on the host header?

**Describe the solution you'd like**
I would like to be able to use different dns names for the same krakend service and select the endpoint based on the host header.

**Describe alternatives you've considered**
Put an ingress controller in front of krakend that changes the path based on the host header. Or run multiple krakend instances, one for each dns host

**Additional context**
n.a.

**Comment by kpacha** [comment]
the enterprise version includes a plugin for dealing with virtualhosts

**Comment by peterzandbergen** [comment]
Thanks for the update.


Peter Zandbergen
Tel: +31 6 460 55 872

linkedIn: peterzandbergen <https://www.linkedin.com/in/peterzandbergen>
