### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by cboitel** [luraproject/lura#506]
**Describe the bug**

Configuring TLS versions to 1.3 (min or max) isn't taken in account and gateway falls back silently to TLS 1.2
Configuring TLS versions to anything leads to the same result

See https://www.krakend.io/docs/service-settings/tls/: TLS13 is listed 

**To Reproduce**

In latest krakend version using lura, set config to include:

```
tls:
  private_key: /xxxx/server.key
  public_key: /xxxx/server.crt
  min_version: TLS12
  max_version: TLS13
```

Krakend/lura ignores TLS13 without warning/error. Using a ssl tool, one can see that TLS 1.3 isn't enabled.

**Expected behavior**

A warning should raised during parsing if version asked isn't supported/valid and documentation should state list of versions supported.
If it is supported, one should be able to enable it.

**Logs**

We tracked down the issue within transport/http/server/server.go:
* parseTLSVersion looks up TLS13 in a map and silently returns TLS12 if nothing was found (line 160)
* the versions map (line 208) does not include the mapping "TLS13' with tls.tls.VersionTLS13 currently defined in tls golang's module.

**Additional context**

Latest TLS version support is required to comply with compliance regulation rules.

**Comment by kpacha** [comment]
nice catch
