### ISSUE TITLE
X-Forwarded-For header not forwarded

### ISSUE THREAD

**Issue by PetarAtFlywheel** [luraproject/lura#515]
**Desciption**
AWS load balancer header value for X-Forwarded-For is not passed through to the back end. Instead it is overwritten by gin. Similarly X-Forwarded-Host is overwritten as well.

If the header is provided it should be passed on (if it is so configured).

Code snippet from lura/gin/endpoint.go

`
  headers["X-Forwarded-For"] = []string{c.ClientIP()}
  headers["X-Forwarded-Host"] = []string{c.Request.Host}
  // if User-Agent is not forwarded using headersToSend, we set
  // the KrakenD router User Agent value
  if _, ok := headers["User-Agent"]; !ok {
	  headers["User-Agent"] = router.UserAgentHeaderValue
  } else {
	  headers["X-Forwarded-Via"] = router.UserAgentHeaderValue
  }
`

**To Reproduce**
1. Configuration used
`
"headers_to_pass":[
    "User-Agent",
    "X-Forwarded-For",
    "X-Forwarded-Proto",
    "X-Forwarded-Host"
],
`
2. Steps to run the software
`
curl --request GET \
  --url https://redacted/__debug/xxx \
  --header 'X-Forwarded-For: 123.234.0.1' 
`

**Expected behavior**

**Logs**
1. Debug logs from Krakend
`
[KRAKEND] 2021/07/22 - 04:44:31.127 [36m▶ DEBUG[0m Method: GET
--
[KRAKEND] 2021/07/22 - 04:44:31.127 [36m▶ DEBUG[0m URL: /__debug/xxx
[KRAKEND] 2021/07/22 - 04:44:31.127 [36m▶ DEBUG[0m Query: map[]
[KRAKEND] 2021/07/22 - 04:44:31.127 [36m▶ DEBUG[0m Params: [{param /xxx}]
[KRAKEND] 2021/07/22 - 04:44:31.127 [36m▶ DEBUG[0m Headers: map[Accept:[*/*] Cookie:[AWSALBCORS=0RLawtjpg4mHuCO7od1cKInYDKIs8mNeIPC4/rNqN72gbHxaOEy0mF0/Kx0uxsFI0DVp/+XOZXPmxqpXOrFu7O7YCvL1yzBr28iSRG/p8HqP9/Ou4nCbMwI0fMLW; AWSALB=0RLawtjpg4mHuCO7od1cKInYDKIs8mNeIPC4/rNqN72gbHxaOEy0mF0/Kx0uxsFI0DVp/+XOZXPmxqpXOrFu7O7YCvL1yzBr28iSRG/p8HqP9/Ou4nCbMwI0fMLW] User-Agent:[insomnia/2021.4.1] X-Amzn-Trace-Id:[Root=1-60f8f7af-58f69d5d3a21c8b86690c11c] X-Forwarded-For:[123.234.0.1, 121.72.114.251] X-Forwarded-Port:[443] X-Forwarded-Proto:[https]]
`

2. Logs from the backend
`
2021-07-22 04:43:57,728 INFO  [redacted] (executor-thread-1) Request headers: [Accept-Encoding=gzip,Host=xxx.:32769,User-Agent=insomnia/2021.4.1,X-Forwarded-For=10.1.3.42,X-Forwarded-Host=redacted,X-Forwarded-Proto=https,X-Forwarded-Via=KrakenD Version 1.4.1]
`

**Comment by alombarte** [comment]
Could you explain what would be the business value of adding the overhead of stacking x-forwarded values?

**Comment by PetarAtFlywheel** [comment]
There are lots of business cases for having the real client IP address (instead of the one of the machine where KrakenD is running on). Geo restrictions, IP rate limiting etc.

I am thinking that this is a bug and not a feature request, since the documentation states that headers are passed through if they are listed in the headers_to_pass property.

**Comment by kpacha** [comment]
@PetarAtFlywheel the current implementation tries as hard as possible to extract the actual client IP (https://github.com/gin-gonic/gin/blob/c7a28f85320125709e47c592a92421a4d6f192a7/context.go#L735-L770), so the only information it's ignoring is the list of load balancers the request passed thru before hitting the gateway

but I see your point, the documentation can be improved

**Comment by PetarAtFlywheel** [comment]
@kpacha So how can the back end get this client IP address? I think the code (rather than the documentation) needs updating. If you want to put krakend IP address somewhere you should use a krakend specific header, and not overwrite one that is already used for a different purpose.

**Comment by PetarAtFlywheel** [comment]
In case someone else runs into the same issue, we added an extra config to our endpoint that copies the header value before it is overwritten:

`
{
  "github.com/devopsfaith/krakend-lua/router": {
    "pre": "local ctx = ctx.load(); ctx:headers('X-Forwarded-For-X', ctx:headers('X-Forwarded-For'));"
  }
}
`
