### ISSUE TITLE
Endpoint variable is not working

### ISSUE THREAD

**Issue by vithubati** [luraproject/lura#527]
**Describe the bug**
when we use the endpoint variable like "endpoint": "/user/{id}" and try to access the endpoint like /user/123, gateway throws 404

**To Reproduce**
1. Configuration used
```
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "no-op",
  "name": "gateway",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/api/accounts",
      "querystring_params":[
        "*"
      ],
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {},
      "headers_to_pass": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "/accounts",
          "encoding": "no-op",
          "method": "GET",
          "extra_config": {},
          "host": [
            "http://localhost:8084"
          ],
          "disable_host_sanitize": false
        }
      ]
    },
    {
      "endpoint": "/api/accounts/{id}",
      "method": "GET",
      "output_encoding": "no-op",
      "backend": [
        {
          "url_pattern": "/accounts/{id}",
          "host": [
            "http://localhost:8084"
          ]
        }
      ]
    }
  ]
}
```
2. Steps to run the software
I used this https://github.com/devopsfaith/krakend-examples/tree/master/chi example with lura

```
	"github.com/luraproject/lura/config"
	"github.com/luraproject/lura/logging"
	"github.com/luraproject/lura/proxy"
	"github.com/luraproject/lura/router"
```

**Expected behavior**
it should route the request to http://localhost:8084

**Logs**
when i run the gateway it loads the endpoint correctly
```
go run services/gateway/old/main.go -d -c services/gateway/old/config.json
2021/10/09 09:29:39 [KRAKEND] DEBUG: registering the endpoint GET /api/accounts
2021/10/09 09:29:39 [KRAKEND] DEBUG: registering the endpoint GET /api/accounts/:id
```

but when i try to access the  /api/accounts/:id i get below error
2021/10/09 09:31:21 "GET http://localhost:8080/api/accounts/3f2 HTTP/1.1" from [::1]:54196 - 404 19B in 303.07µs

**Additional context**

**Comment by kpacha** [comment]
I think that example is not setting the configuration as required by the router. This integration test does it ok: https://github.com/luraproject/lura/blob/master/test/integration_test.go#L79

**Comment by vithubati** [comment]
Thanks setting the `config.RoutingPattern = config.BracketsRouterPatternBuilder`, before loading the config worked.
