### ISSUE TITLE
Receiving 500 error when the backend returns 204

### ISSUE THREAD

**Issue by SubalaNarayanamurthyJisc** [luraproject/lura#535]
**Describe the bug**
My backend api returns a response with empty response body and a response code 204, which the krakenD interprets as an error response thus sends 500-internal server error back. 
I tried using no-op encoding, even after that I have been getting the error Error #01 EOF
For some reason KrakenD doesnt like empty response, as everything works fine if I change my backend api response to have a response body. 

**Expected behavior**
Krakend should allow the empty response and also should allow 204 as a success response code. 

Any help would be much appreciated, TIA.

**Comment by alombarte** [comment]
Hi,

The 204 status code comes without a body by definition. Please see the RFC entry https://www.rfc-editor.org/rfc/rfc9110#section-15.3.5-5

>    A 204 response is terminated by the end of the header section; it cannot contain content or trailers.

So it would fail when trying to parse the response anyway and produce a 500 too even if we added it as a success code. The output encodings require you to provide data. When there is no body, and you don't need to do any modifications, then no-op does the job.
