### ISSUE TITLE
Service Discovery based on A records in addition to SRV

### ISSUE THREAD

**Issue by davide-romanini-milkman** [luraproject/lura#538]
**Is your feature request related to a problem? Please describe.**
We already have backend services using multivalue A records, but Krakend/Lura only supports SRV and our current deployment solution doesn't allow registration of both kind of records.

**Describe the solution you'd like**
It should be possible to configure dns service discovery to use `LookupHost` instead of only `LookupSRV` and update the host slice based on A records.

**Describe alternatives you've considered**
We can just use `static` and let the DNS round robin the hosts, but that is suboptimal and causes service disruption during deployments because Krakend/Lura seems to route requests on stale hosts.

**Additional context**
None.

**Comment by kpacha** [comment]
hi, @davide-romanini-milkman 

the main issue with A records is that they do not provide a port, weight nor priority for each host. So I think they should not be used through krakend but through the underlaying operating system.

If you want to use those A records, I recommend you to define your hosts at krakend as static and let your OS dns resolver to do the discovering and balancing
