### ISSUE TITLE
Request Response Modifier doesn't work in the same go file

### ISSUE THREAD

**Issue by trojanh** [luraproject/lura#547]
**Describe the bug**
I have created a [repo](https://github.com/trojanh/krakend-plugin-modifier/blob/master/plugins/krakend-debugger.go) here which replicates the [new plugin modifier ](https://www.krakend.io/docs/extending/plugin-modifiers/)as mentioned in docs 

when we use this plugin to run the krakend configuration, it only attaches the first modifier created inside the RegisterModifier method in the above example [its request modifier](https://github.com/trojanh/krakend-plugin-modifier/blob/master/plugins/krakend-debugger.go#L33).

I tried to use the different names for both the modifier by following the doc like mentioned in the #543 

```
    f(string(r)+"-request", r.requestDump, true, false)
    f(string(r)+"-response", r.responseDump, false, true)
```

but even this is only registering the 1st modifier, 

when I comment out the 1st modifier , 2nd one starts working.

So it seems like only one plugin modifier will work for given RegisterModifiers

**To Reproduce**
1. Configuration used :  https://github.com/trojanh/krakend-plugin-modifier/blob/master/krakend.plugin.json

**Expected behavior**
Ideally both the modifier should have worked to handle the request and response.

**Comment by kpacha** [comment]
the documentation contained some errors and was updated some days ago. please, check again the response wrapper interface and avoid using the same name for both modifiers

**Comment by trojanh** [comment]
hey @kpacha I had done most of the changes but I verified again  from the doc and I got following logs, which clearly indicates none of the modifier were loaded if I use the same modifier code.

which clearly 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22974490/158394976-02373c95-e420-4ed2-b6ff-b12af27b6482.png">

after which I replaced below  line 

```
f(string(r)+"-request", r.requestDump, true, false)
f(string(r)+"-response", r.responseDump, false, true)
```
with this 

```
f(string(r)+"-request", r.requestDump, true, false)
f(string(r), r.responseDump, false, true)
```

and now the the response modifier started working but request modifier still did not work as it has different name maybe ?.

**Comment by trojanh** [comment]
I am not sure but does have something to do with this line ?
https://github.com/luraproject/lura/blob/633684c4153c429a62fe7299b401dbdf9a1dc811/proxy/plugin/modifier.go#L47

**Comment by kpacha** [comment]
don't forget to add the proper plugin names on your configuration (krakend-debugger-request & krakend-debugger-response)

**Comment by trojanh** [comment]
I guess that was the missing, seems to be working now thanks @kpacha 

here is the working example 
https://github.com/trojanh/krakend-plugin-modifier/blob/master/krakend.plugin.json

Also updated the missing documentation for this along with updated example configuration
https://github.com/devopsfaith/krakend-documentation/pull/150
