### ISSUE TITLE
Routing by header or request params more generally

### ISSUE THREAD

**Issue by sashahilton00** [luraproject/lura#569]
Hi,

I have been reading through the documentation for Krakend whilst evaluating it as part of a move from an existing API gateway. One of the things that we are looking to do is to route by header - the scenario looks something like as follows:

The proxy checks if the header `X-API-Version` is supplied, which itself is of the format `2020-11-19`, and routes according to the backend that has the most recent API version that existed before the defined date. If no header is supplied, the user details are queried and cached, and the `X-API-Version` header is populated with the creation date of the user's account.
 
Is this something that is possible with Krakend? Routing by method appears to be well documented, but routing by header contents does not appear to be documented anywhere. The closest I have come to finding information on it is in #308 where it states:

```
Routing by header is not a recommended strategy but can be implemented using a custom martian modifier or http client plugin
```

However, further exploration does not provide any hints as to how one can influence which backend handles a request based on the header.

Edit: I realise the above behaviour of logic comparisons may be a bit beyond the scope of Krakend. We do not have that many different versions, and these could be provided as a static map, so the above question could be distilled, if necessary, into: 'Is it possible to use a header value to map a request to a specific backend?'

**Comment by alombarte** [comment]
Hi @sashahilton00 , you opened this issue long time ago before KrakenD Framework was donated to the Linux Foundation. KrakenD implemented header routing a long time ago: https://www.krakend.io/docs/enterprise/endpoints/dynamic-routing/#routing-based-on-headers
