### ISSUE TITLE
plugin was built with a different version of package github.com/luraproject/lura/v2/register

### ISSUE THREAD

**Issue by krishna-kunderu** [luraproject/lura#570]
Describe what are you trying to do
Using the github.com/luraproject/lura/v2/proxy for request/response modifier plugin following below KrakenD suggested document.

Modifier plugin is not getting registered with the below errors. Looks like some of the below libraries mentioned in go.mod as below are not built with the GO version our project is using. Not sure how to overcome this. If I remove proxy.ResponseMetadataWrapper from the ResponseWrapper interface all working fine. I am not sure how to build the proxy package provided by lura to make it compatible with Go 1.17.8.

Tried with both v2 and 1.4.1 but giving same errors

V2 with below go.mod giving below errors

go 1.17

require ( plugin was built with a different version of package github.com/luraproject/lura/v2/register )

2022/04/11 08:53:56 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin"): plugin was built with a different version of package github.com/luraproject/lura/v2/register

V1.4.1 with below go.mod giving below errors

go 1.17

require ( github.com/devopsfaith/flatmap v0.0.0-20200601181759-8521186182fc // indirect github.com/luraproject/lura v1.4.1 // indirect github.com/valyala/fastrand v1.0.0 // indirect )

https://www.krakend.io/docs/extending/plugin-modifiers/

Your configuration file

Go Lang version tried with 1.17.8
Used this below command to build .so plugin

go build -buildmode=plugin -o modifierPlugin.so modifierPlugin.go

Logs
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin https://github.com/devopsfaith/krakend-ce/pull/1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin"): plugin was built with a different version of package github.com/valyala/fastrand
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Handler Plugin] plugin https://github.com/devopsfaith/krakend-ce/pull/1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin.so"): plugin was built with a different version of package github.com/valyala/fastrand (previous failure)
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #0 (/etc/krakend/plugins/httpHandlerPlugin.so): plugin: symbol ModifierRegisterer not found in plugin plugin/unnamed-be415b995a80d55a5fde08e3201bb850429c9287
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin https://github.com/devopsfaith/krakend-ce/pull/1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin.so"): plugin was built with a different version of package github.com/valyala/fastrand (previous failure)

**Comment by krishna-kunderu** [comment]
I have added all dependencies but still giving error

`plugin was built with a different version of package github.com/luraproject/lura/v2/register`

![image](https://user-images.githubusercontent.com/99324244/162991877-6d6c7975-3548-45cb-8bd7-862e810b3508.png)

**Comment by kpacha** [comment]
if you need more examples, please check this one from the community: https://github.com/trojanh/krakend-plugin-modifier/blob/master/plugins/krakend-debugger.go

**Comment by krishna-kunderu** [comment]
Actually using the sane example. All works fine if I dont use proxy.ResponseMetadataWrapper
So if i comment related to proxy i could see request and response going fine through plugin

I see the error only when i use the proxy import to access Headers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by krishna-kunderu** [comment]
I still couldn't resolve this issue and couldn't find the solution for this. Not sure what dependency the modifier plugin is looing for

**Comment by krishna-kunderu** [comment]
The issue is now resolved with v2.0.3 after deprecating Metadata. Thanks for fixing this.

Is there a way to change the HTTP StatusCode in response modifier plugin. I could able to modify Data with corresponding custom error structure, but I can't update the status code to the value I want to set in the responseModifier.

**Comment by taik0** [comment]
Hi @krishna-kunderu 

Since the root of the issue has been resolved, let's close this issue and discuss anything new in a new issue or via mailing-list/slack.

Thank you!

**Comment by kpacha** [comment]
@krishna-kunderu if you are not using a `no-op` pipe, status code is ignore by the renderer.

if you want to return a custom error code, do not alter the response, throw an error implementing this interface: https://github.com/luraproject/lura/blob/master/router/gin/endpoint.go#L160-L163

**Comment by krishna-kunderu** [comment]
How do we throw an HTTP error from modifier plugin, I do not see context or ResponseWriter in the modifier plugin?

**Comment by krishna-kunderu** [comment]
@kpacha Even if implement the error interface you mentioned, the status code is not changed in the response from the modifier plugin.

**Comment by kpacha** [comment]
if you return an error and a nil response, it should use just the error to build the final response to the client. you can check the related code: https://github.com/luraproject/lura/blob/master/router/gin/endpoint.go#L71-L92

**Comment by krishna-kunderu** [comment]
Yes indeed I used the same example and used the interface to send error, statuscode and nil data. But the modifierPlugin when return nil, customErrorResponse, is giving only 500 response with Internal Error. Ideally I would like to show response as 
{
  message: "some error messages",
  reason: "detail reason"
  code: "error code"
} and have the HTTP status code as 400. As modifier plugin do not have any context or response writer, I couldn't even write the custom error message.

It would be great modifier plugin has capability to update error message in body and corresponding custom StatusCode in the response. Modifier Plugin seems much useful only to do logging the request/response, not exactly doing what it says (to transform response).

**Comment by kpacha** [comment]
@krishna-kunderu please, can you share your error type? if it implements the interface `responseError` (https://github.com/luraproject/lura/blob/396ee1e92a14aae8d8fad8e05c0086ed5ec33f67/router/gin/endpoint.go#L160-L163) the endpoint should be returning the error code it contains (see the code linked in my previous comment).

also, as @taik0 pointed out, this is not the place for this conversation because we are polluting the original issue. please, open a new one and link it to this so we can continue over there
