### ISSUE TITLE
examples folder missing?

### ISSUE THREAD

**Issue by shivahnshankar** [luraproject/lura#591]
**Describe the bug**
The README under "Library Usage" states that there is an examples folder. However this seems to be missing.

**To Reproduce**
Check for existence of examples folder

**Expected behavior**
examples folder exists or documentation is updated

**Logs**
NA

**Additional context**
NA.

**Comment by juan-chan** [comment]
I don't see the sample folder either.. Where should I look for it?

**Comment by kpacha** [comment]
The examples were moved some time ago to a dedicated repo (that is no longer maintained) https://github.com/devopsfaith/krakend-examples

for more updated examples, you can check the [KrakenD-CE](https://github.com/krakendio/krakend-ce) repo

**Comment by pavlovmike** [comment]
How about fixing README with the correct link to examples?

**Comment by kpacha** [comment]
I removed the reference and just linked the KrakenD CE repo
