### ISSUE TITLE
Can Krakend handle Api Orchestration support concurrent mode and sequential mode in one endpoint (mix mode)

### ISSUE THREAD

**Issue by chchgb** [luraproject/lura#595]
Is there anyone can help me to build one endpoint with below scenario？

backend A -----> backend B(rely on the result from A)  -----> backend D(rely on the result from both B and C)  
                   -----> backend C(rely on the result from A)

much like the mix model in rule engine 

similar issues:
https://github.com/krakendio/krakend-ce/issues/176
https://github.com/luraproject/lura/issues/182

**Comment by alombarte** [comment]
Hi @chchgb , you can achieve this by creating intermediate endpoints, but there are no plans to support this feature using a single endpoint
