### ISSUE TITLE
Question: Streaming the response body to the client without a full load using the client plugin is not supported.

### ISSUE THREAD

**Issue by iamakoreandeveloper** [luraproject/lura#602]
Hello team.
I am using krakend 1.4.1 and client plugin.
When downloading a binary file using the client plugin, it is fully loaded without streaming to the client.
Please let me know the solution.

**Comment by kpacha** [comment]
If you don't want that binary data flow through your gateway, send that from a handler plugin instead of doing it from a client plugin
