### ISSUE TITLE
AMQP producer, consumer, and async agents do not support enough parameters

### ISSUE THREAD

**Issue by tlloydthwaites** [luraproject/lura#605]
(Based on discussion with Albert Lombarte on slack)

**Is your feature request related to a problem? Please describe.**
When creating an AMPQ producer/consumer or an async agent in KrakenD to connect to RabbitMQ, there are not enough parameters to support common RabbitMQ settings. In particular, connecting to an existing exchange with 'alternate-exchange' defined will cause:

```
Reason: "PRECONDITION_FAILED - inequivalent arg 'alternate-exchange' for exchange 'XXX' in vhost 'XXX': received none but current is the value 'some-other-exchange' of type 'longstr'"
```

This is particularly problematic when defining queues with a dead-letter exchange. This is important for many queues, but a producer can't connect to it because of mismatched args.

**Describe the solution you'd like**
Ideally, we would be able to pass all currently-supported parameters. For exchanges this is only 'alternate-exchange', but for queues there is:
- type (classic, quorum, stream)
- x-message-ttl
- x-expires
- x-overflow
- x-single-active-consumer
- x-dead-letter-exchange
- x-dead-letter-routing-key
- x-max-length
- x-max-length-bytes
- x-max-priority
- x-queue-mode
- x-queue-master-locator

Since these are simple key/value pairs, would it be possible to just pass any "x-" parameter straight to Rabbit?

**Describe alternatives you've considered**
- For producing messages, we are able to use the RabbitMQ HTTP API to send a message via POST. However this is not ideal as it is slower, and it requires clients to either send a full AMPQ envelope (which tightly-couples them to Rabbit) or use Martian to modify the POST payload (which we'd rather not do as we would prefer to keep the endpoint no-op).
- At present, we are unable to receive messages via Async Agents from queues defined with a DLX (or any other property that KrakenD does not support).

**Comment by alombarte** [comment]
Hi @tlloydthwaites 

If you are still interested in this functionality, please create this issue on [krakend-amqp](https://github.com/krakend/krakend-amqp), but it will be very-low priority
