### ISSUE TITLE
Disable encoding of query parameters in the load balancing middleware

### ISSUE THREAD

**Issue by RubyKozel** [luraproject/lura#634]
**Describe the bug**
Hey,
This is in continuation to a bug I created in the krakend-ce project. (https://github.com/krakendio/krakend-ce/issues/648)
Seems like your load balancing middleware is encoding every query parameter, leading to backends receiving wrong query parameters:
https://github.com/luraproject/lura/blob/master/proxy/balancing.go#L69-L75 
I don't really understand why you need to touch the query parameters, but we at least should have the option to disable this behavior

**To Reproduce**
1. Create any endpoint with any backend. E.g endpoint: /foo, backend: /bar
2. call /foo?filter=a%20eq%20

**Expected behavior**
the backend /bar should receive the query as is, meaning /bar?filter=a%20eq%20

**Actual Behavior**
the backend /bar receives the query with the %20 being replaced with '+', meaning /bar?filter=a+eq+b

**Logs**
If applicable, any logs and debugging information

**Additional context**

**Comment by kpacha** [comment]
I do not see that as a bug. It's a design choice because the encoding should be resolved in some way. Your proposal is as opinionated as the solution applied in lura but it adds more operations to the pipe.

Please, check this snippet https://go.dev/play/p/DOAKtWKhpqV. You'll see that, for the 3 possible ways to encode your querystring, both implementations are equally consistent

Thanks for taking the time contributing.

**Comment by RubyKozel** [comment]
@kpacha sorry, but I'm not very sure I understand what you're saying.
This design choice enforces the users of your gateway to pass wrong query parameters to the backends. There are scenarios where backends expect to receive the query parameters as is.
This is not something you should enforce, especially when dealing with something as sensitive as query parameters. This should be at the very least the default behaviour with a way to disable it. 

In your snippet you can clearly see that when you encode "%20" they turn into "+" signs, while in my proposal the query stays the same. 
Currently, this "feature" makes your gateway be unusable unless we fork it and change this behaviour.

**Comment by alombarte** [comment]
Hi @RubyKozel , you indicated in the body of the issue that we shouldn't touch the query string parameters, yet your PR touches them twice, using two operations that affect performance.

It also changes (breaks) the way query strings are processed today (in two million servers month), and it does not offer any safe way or flag to enable/disable the new behavior.

I also must disagree with your sentence:
> Currently, this "feature" makes your gateway be unusable unless we fork it and change this behaviour."

We cannot accept the PR as it breaks behavior, and it does not offer an alternative. If you need to fork the project, this is the essence of open source, it's fine with us.

**Comment by RubyKozel** [comment]
Hi @alombarte 
I'm not telling you to accept the PR. The PR shows one way of keeping the query parameters as they were originally received by the client, which was his sole purpose. I'm sure there are other, intelligent ways of doing that. I didn't dig that deep into your code.
The focus of this issue shouldn't be the PR but the problem that the current code creates. 
As you are the code owners, I'm sure you have more insights and knowledge of how to make this configurable at the very least.

We're already forking your solution, but that is currently preventing us from moving to the Enterprise edition, as we see there are issues, like the one described here, that we cannot accept.

**Comment by alombarte** [comment]
Hi @RubyKozel

I am wearing the Lura hat now. KrakenD donated this repository to The Linux Foundation a while ago, and although KrakenD uses this library, and I work at KrakenD, whatever issue you have with KrakenD (Enterprise or not), it's entirely irrelevant for Lura.

Lura is a project driven by the community, and BUILT by the community, and KrakenD is PART of this community. It might propose something to Lura if it fits into the project philosophy. But there are many more companies using this library (even other commercial API gateways), and we need to be very cautious about not breaking things.

Pull requests and issues in this repository are reviewed and are meant to be something mergeable, or at least iterable. But not "ideas" expecting that someone else solves your problem. "One company issues" are rarely accepted as they don't benefit the community and add more complexity to the project, and it seems to us that this is the case.

If you are willing to rework the PR so the existing user base is unaffected, we might accept it. If you want KrakenD to do this for you, then get in touch, and let's talk about a commercial agreement.

**Comment by RubyKozel** [comment]
Hi @alombarte 

I've reworked the PR so that it is configurable to disable the encoding.
Would appreciate your comments and improvement suggestions.
Thanks.

**Comment by RubyKozel** [comment]
@alombarte 
I've just realized after debugging the code that the root cause is actually here: https://github.com/luraproject/lura/blob/master/router/gin/endpoint.go#L148
The query is being decoded from "a%20b" to "a b" and then it's being encoded to "a+b" in the load balancer middleware
unfortunately, my solution will not give the proper query value for situations where the query parameters are not encoded

Since I don't have time to invest in this, I will close the PR and rethink the solution in another time

Thanks.

**Comment by alombarte** [comment]
Ok @RubyKozel ,

Whenever you have the time to review it again, I just wanted to comment that in the [PR you closed](https://github.com/luraproject/lura/pull/645/files), you changed the signature of the library. You cannot enforce new parameters in existing functions as this breaks compatibility. Keep it in mind for future contributions.

I am closing this issue as no one from Lura will work on this. But you are welcome to contribute again, create a new issue (if this reaches the locking time), and reference it.
