### ISSUE TITLE
GraphQL backend to support variables in the POST body for Queries 

### ISSUE THREAD

**Issue by NavidMitchell** [luraproject/lura#641]
Would the Lura team be open to a patch that allows the GraphQL backend to support variables provided in the body of a POST for GraphQL queries? Currently this is only supported for mutations. 

See the docs here https://www.krakend.io/docs/backends/graphql/

**Comment by kpacha** [comment]
The types are for easier reasoning when building your endpoints but they do not enforce anything on the queries to send, so you can send a query using the `mutation` type
