### ISSUE TITLE
Probably me as newbie but I can't get the GraphQL proxy config to work

### ISSUE THREAD

**Issue by stevef1uk** [luraproject/lura#642]
As someone new to Krakend I have followed the documentation on configuring a GraphQL proxy and all I can see if a log message showing '[GIN] 2023/02/23 - 08:27:36 | 404 |       4.833µs |       127.0.0.1 | POST     "/graphql"

I am testing via curl and just receive a '404 page not found%' error

I have listed my config in case some kind soul can give me some pointers. I have changed my admin password below for obvious reasons :-) I may not have configured the header I need correctly either, but I haven't got that far yet.

config (which I checked to ensure ok via the kraken check tool):

```
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "KrakenD - API Gateway",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "endpoint": "/graphql",
	"input_query_strings":["*"],
	"backend": [
        {
            "timeout": "4100ms",
            "host": ["https://api.sjfisher.com/v1"],
            "url_pattern": "/graphql?timeout=4s",
            "extra_config": {
              "backend/http": {
                  "return_error_details": "backend_alias"
              },
              "modifiers": [
                {
                    "header.Modifier": {
                        "scope": ["request"],
                        "name" : "x-hasura-admin-secret",
                        "value" : "<my secret here>"
                    }
                }
              ]
          }
        }
    ]
}
```

**Comment by kpacha** [comment]
your config is missing the `endpoints` section, so no endpoint is being defined (and that's why you're getting a 404). If you want to fully validate your config, use the linter by adding the `-l` flag in the checker: `krakend check -dlc <your_config.json>`

If you are new to krakend, you could use the designer (http://designer.krakend.io) to get the first draft of your config

**Comment by stevef1uk** [comment]
Thanks. I did try that but just found before reading this that I could use the "no-op" approach which worked well.
