### ISSUE TITLE
Where did the examples go?

### ISSUE THREAD

**Issue by ijsnow** [luraproject/lura#684]
**Describe the bug**

The [links to the two examples here](https://github.com/luraproject/lura/blob/master/docs/README.md#examples) result in a 404.

**To Reproduce**
1. Go to https://github.com/luraproject/lura/blob/master/docs/README.md#examples
2. Click a link to the examples.

**Expected behavior**
Links take you to examples.

**Logs**
N/a

**Additional context**
I've searched for directories in the repo with examples in the path and didn't find anything.

**Comment by kpacha** [comment]
Thanks for bringing it to our attention! 

Maintaining all the examples was too costly so, initially we remove them from the repo and, latter, we even stop maintaining the repo https://github.com/devopsfaith/krakend-examples. We though that the best and most detailed example was the [krakend CE repository](https://github.com/krakend/krakend-ce) (where all the potential of the framework is used).

I'll keep the issue open until we remove all the dead links

**Comment by ijsnow** [comment]
Ah fair enough! Good old fashion code search for references of functions you want to use should do the trick.
