### ISSUE TITLE
Gofiber Support

### ISSUE THREAD

**Issue by efectn** [luraproject/lura#691]
**Is your feature request related to a problem? Please describe.**
It adds new router to lura.

**Describe the solution you'd like**
[Fiber](https://github.com/gofiber/fiber) is a framework that's faster than net/http alternatives. I think it might be useful for HTTP/1 API gateway usecases.

**Describe alternatives you've considered**
If you are OK to implement new router based on FastHTTP, i can give it a try to implement Fiber for Lura.

**Additional context**
![2023-10-07_10-25](https://github.com/luraproject/lura/assets/45270788/3bf6dde6-03d5-497b-b5ca-9dc1a68245d9)

![go benchmarks](https://raw.githubusercontent.com/smallnest/go-web-framework-benchmark/master/benchmark.png)

**Comment by alombarte** [comment]
Hi @efectn,

At KrakenD (not under Lura), we did tests with Fiber. Here's a related conversation: https://github.com/krakend/krakend-ce/issues/724#issuecomment-1536404664

Lura currently supports several router implementations I am not sure anyone is using, but given the size of the team and the lack of volunteers to maintain other open-source routers, we will need to make a decision and shrink options. Still, Fiber is an interesting one.

**Comment by kpacha** [comment]
This is a great idea and the pkg looks promising but, after some testing, we have found some issues with how gofiber deals with json encoding and in other areas, so we have discarded the swap.

On the other hand, we are working on the v3 and the current plan is to remove all router implementations and stick with the new mux from the stdlib.

Thanks for the suggestion!
