### ISSUE TITLE
Mixed paths when performing multiple backend calls in parallel for a given Endpoint

### ISSUE THREAD

**Issue by ramonibz** [luraproject/lura#719]
**Describe the bug**
Having and endpoint defined with two backends to make the backend calls in parallel, we have found that sometimes (under some race condition) the call to booth backends is done with the same path (url_pattern)

**To Reproduce**

This issue occurs with version 2.6.1 of lura, version 2.6.0 seems to work well

The issue is not reproducible 100% of the times. After some test it seems it appears randomly but we can reproduce it around 5% of the times.

Example configuration endpoint:
```json
{
    "endpoint": "/test",
    "input_headers": [
        "*"
    ],
    "method": "GET",
    "backend": [
        {
            "group": "1",
            "host": [
                "http://httpbin.org"
            ],
            "url_pattern": "/user-agent"
        },
        {
            "group": "2",
            "host": [
                "http://httpbin.org"
            ],
            "url_pattern": "/ip"
        }
    ]
}
```
With the above configuration you can make calls to the `/test` endpoint and around 5% of the times you should be able to reproduce the issue.

When the call to the `/test` endpoint works ok the result is the following:
```
curl http://localhost:8090/test
{"1":{"user-agent":"curl/8.4.0"},"2":{"origin":"::1, 0.0.0.0"}}
```
When the issue appears due to some race condition, the result is:
```
curl http://localhost:8090/test
{"1":{"origin":"::1, 0.0.0.0"},"2":{"origin":"::1, 0.0.0.0"}}
```
or:
```
curl http://localhost:8090/test
{"1":{"user-agent":"curl/8.4.0"},"2":{"user-agent":"curl/8.4.0"}}
```
\* IPs have been obfuscated to 0.0.0.0 for privacy  

**Expected behaviour**
Expected behaviour is that when having an endpoint with multiple calls in parallel to backends, each call to each backend honors the defined url_pattern in the endpoint configuration.

For the above endpoint configuration example, the expected behaviour is to have a response like this one:
`{"1":{"user-agent":"curl/8.4.0"},"2":{"origin":"::1, 0.0.0.0"}}`

**Additional context**
After some debugging, it seems that this [change](https://github.com/luraproject/lura/pull/714/files#diff-b3e1c3bd7270e3a4f7dd601d1f23173fd89ae27359a0c30b00216144ad039cc2L118) could have introduced the issue because the request is not being cloned anymore and this function is used for every backend call modifying the path of the request object which could be the cause of the bug because the request (r) is passed to the function as a reference.
```go
return func(ctx context.Context, r *Request) (*Response, error) {
			r.GeneratePath(remote.URLPattern)
			r.Method = remote.Method
                         return next[0](ctx, r)
```

**Comment by kpacha** [comment]
thanks for the heads up!!! I think we have a fix ready for this. We'll test it a little more and release v2.6.2 ASAP
